#!/bin/bash

export EGSH_DIR ;
export EGSH_VERSION ;
export EGSH_USR_DIR ;
export EGSH_USR_INC ;
export EGSH_USR_SRC ;
export EGSH_USR_ENV ;


export EGSH_CTX_ESYNC_LIB ;    
export EGSH_CTX_DCMD_LIB ;
export EGSH_CTX_PKG_LIB ;

EGSH_OWNER_ID=$(stat -c %u $EGSH_DIR)

echo "<< EGSH Launch - DCMD(Delayed Command) background >>"
sleep 1

for i in $( find $EGSH_USR_DIR/dcmd -type f )
do
    echo ""
    echo "<< EGSH Launch - $i background >>"
    if [ $EGSH_OWNER_ID -eq 0 ] ; then
        echo "sudo chmod +x $i"
        echo "sudo $i &"
        #sudo chmod +x $i
        sudo $i &
    else 
        echo "chmod +x $i"
        echo "$i &"
        #chmod +x $i
        $i &
    fi
done




